# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'EzMoney' do
pod 'Alamofire', '~> 3.0'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'

end

target 'EzMoneyTests' do

end

target 'EzMoneyUITests' do

end

